#!/usr/bin/env python3
"""Retired compatibility entry point for direct ComfyUI model transfer.

Default transport:
  source HTTPS -> Meifu 2 GiB resumable chunk -> local SFTP reget -> staging
  -> SHA-256 verification -> atomic move into the selected ComfyUI model root.

New model transfers are prepared by ``delegate_model_downloads.py`` and carried
out only by the generic ``meifu-resumable-download`` Windows queue.  This file
keeps the former command shape for safe migration messages, but never opens an
SSH/SFTP connection or writes a model.
Use a dependency report generated by ``audit_model_dependencies.py`` whenever
possible, so category and source URL come from the template rather than guesswork.
"""

from __future__ import annotations

import argparse
import base64
from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from typing import Any
from urllib.parse import urlsplit, urlunsplit

from model_paths import (
    DEFAULT_FALLBACK_ROOT,
    DEFAULT_PRIMARY_ROOT,
    DEFAULT_PRIMARY_THRESHOLD_GIB,
    DEFAULT_SHARED_PATHS,
    StorageSelection,
    choose_primary_and_fallback,
    choose_storage,
    ensure_safe_category,
)


DEFAULT_HOST = "meifu主机"
DEFAULT_REMOTE_CACHE = "/root/.cache/comfyui-models"
DEFAULT_CHUNK_GIB = 2
DEFAULT_REMOTE_RESERVE_GIB = 4
DEFAULT_LOCAL_RESERVE_GIB = 10
TEMPORARY_TRANSFER_EXIT_CODE = 74
DEFAULT_CATALOG = Path(
    r"D:\12070\Documents\workspaces\Comfy-Codex-Workspace\models\catalog.json"
)
MODEL_SUFFIXES = {".safetensors", ".ckpt", ".pth", ".pt", ".bin", ".gguf", ".onnx"}
SHA256_RE = re.compile(r"(?i)^[0-9a-f]{64}$")


class DownloadError(RuntimeError):
    """Expected, user-actionable download failure."""


class TransferUnavailable(DownloadError):
    """A transient SSH/SFTP/source-network failure; preserving resumable state is safe."""


class PauseRequested(DownloadError):
    """A durable queue asked this transfer to stop at the next safe boundary."""


# These messages indicate a transport outage or a retryable upstream response.
# Authentication, permissions, a missing source file, storage exhaustion and
# integrity errors intentionally remain permanent DownloadError failures.
TRANSIENT_TRANSFER_PATTERNS = (
    "unknown error",
    "connection timed out",
    "operation timed out",
    "connection reset",
    "connection refused",
    "connection closed",
    "connection lost",
    "connection aborted",
    "network is unreachable",
    "no route to host",
    "could not resolve host",
    "temporary failure in name resolution",
    "kex_exchange_identification",
    "broken pipe",
    "ssh: connect to host",
    "connection to ",
    "the requested url returned error: 408",
    "the requested url returned error: 425",
    "the requested url returned error: 429",
    "the requested url returned error: 500",
    "the requested url returned error: 502",
    "the requested url returned error: 503",
    "the requested url returned error: 504",
    "http 408",
    "http 425",
    "http 429",
    "http 500",
    "http 502",
    "http 503",
    "http 504",
)
PERMANENT_TRANSFER_PATTERNS = (
    "permission denied",
    "authentication failed",
    "host key verification failed",
    "the requested url returned error: 400",
    "the requested url returned error: 401",
    "the requested url returned error: 403",
    "the requested url returned error: 404",
    "http 400",
    "http 401",
    "http 403",
    "http 404",
    "no space left on device",
)


def is_transient_transfer_detail(detail: str, *, returncode: int | None = None) -> bool:
    """Classify only clearly retryable transfer errors.

    The caller keeps local and remote partial files untouched when this returns
    true.  A failed SSH process commonly exits 255; for curl remote scripts the
    meaningful HTTP message is used instead.
    """

    normalized = detail.casefold()
    if any(pattern in normalized for pattern in PERMANENT_TRANSFER_PATTERNS):
        return False
    if returncode == 255:
        return True
    return any(pattern in normalized for pattern in TRANSIENT_TRANSFER_PATTERNS)


@dataclass(frozen=True)
class DownloadRequest:
    filename: str
    category: str
    source_url: str
    expected_sha256: str | None
    workflows: tuple[str, ...]

    @property
    def safe_url(self) -> str:
        parts = urlsplit(self.source_url)
        return urlunsplit((parts.scheme, parts.netloc, parts.path, "", ""))

    @property
    def url_hash(self) -> str:
        return hashlib.sha256(self.source_url.encode("utf-8")).hexdigest()

    @property
    def job_id(self) -> str:
        stem = re.sub(r"[^A-Za-z0-9_.-]+", "-", Path(self.filename).stem).strip("-.")
        return f"{stem[:56]}-{self.url_hash[:12]}"


def gib(value: float) -> int:
    if value <= 0:
        raise DownloadError("GiB 参数必须大于 0。")
    return int(value * 1024**3)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def atomic_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(f".{path.name}.tmp")
    temp.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temp, path)


def read_transfer_control(control_file: Path | None) -> str | None:
    """Read the queue control file without changing it.

    Only ``pause`` and ``stop`` are actionable.  The caller intentionally checks
    this only between transfer steps: killing a live SFTP/SSH process would make
    recovery less predictable, while this still leaves at most one remote chunk.
    """

    if control_file is None or not control_file.exists():
        return None
    try:
        payload = json.loads(control_file.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError) as exc:
        raise DownloadError(f"下载控制文件无效：{control_file}") from exc
    action = str(payload.get("action", "")).strip().lower()
    return action if action in {"pause", "stop"} else None


def ensure_transfer_not_paused(control_file: Path | None) -> None:
    action = read_transfer_control(control_file)
    if action:
        raise PauseRequested(f"队列请求{action}，已在安全边界暂停传输。")


def ssh_effective_config(host: str) -> dict[str, str]:
    """Return the effective OpenSSH config used by both ssh and sftp."""

    result = subprocess.run(
        ["ssh", "-G", host],
        text=True,
        capture_output=True,
        encoding="utf-8",
        errors="replace",
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        raise DownloadError(f"无法读取 SSH 连接配置：{detail[-800:]}")
    config: dict[str, str] = {}
    for line in result.stdout.splitlines():
        key, separator, value = line.partition(" ")
        if separator:
            config[key.strip().lower()] = value.strip()
    return config


def ensure_direct_meifu_route(host: str, expected_hostname: str, allow_proxy_route: bool) -> dict[str, str]:
    """Refuse an SSH ProxyJump/ProxyCommand route unless explicitly overridden."""

    config = ssh_effective_config(host)
    proxy_command = config.get("proxycommand", "none").strip().lower()
    proxy_jump = config.get("proxyjump", "none").strip().lower()
    effective_host = config.get("hostname", "").strip()
    if not allow_proxy_route and (proxy_command not in {"", "none"} or proxy_jump not in {"", "none"}):
        raise DownloadError("SSH 配置包含 ProxyJump 或 ProxyCommand；为避免经 CN2 中转，已拒绝下载。")
    if expected_hostname and effective_host != expected_hostname:
        raise DownloadError(
            f"SSH 别名 {host} 解析到 {effective_host or '空'}，不是要求的美服直连地址 {expected_hostname}。"
        )
    return {
        "alias": host,
        "hostname": effective_host,
        "port": config.get("port", ""),
        "proxycommand": proxy_command,
        "proxyjump": proxy_jump,
        "direct_config_verified": not allow_proxy_route,
    }


def normalize_sha256(value: str | None) -> str | None:
    if not value or value.lower() == "auto":
        return None
    value = value.strip().strip('"').lower()
    if not SHA256_RE.fullmatch(value):
        raise DownloadError("expected_sha256 必须是 64 位十六进制值或 auto。")
    return value


def normalize_download_url(source_url: str) -> str:
    """Turn a Hugging Face web-view link into its immutable file endpoint."""

    parts = urlsplit(source_url)
    segments = parts.path.split("/")
    if parts.netloc.lower().endswith("huggingface.co") and "blob" in segments:
        index = segments.index("blob")
        segments[index] = "resolve"
        return urlunsplit((parts.scheme, parts.netloc, "/".join(segments), parts.query, ""))
    return source_url


def validate_request(
    filename: str,
    category: str,
    source_url: str,
    expected_sha256: str | None,
    workflows: list[str] | tuple[str, ...] = (),
) -> DownloadRequest:
    filename = Path(filename).name
    if not filename or Path(filename).suffix.lower() not in MODEL_SUFFIXES:
        raise DownloadError("模型文件名必须是单个受支持的模型文件名，不能包含目录。")
    category = ensure_safe_category(category)
    source_url = normalize_download_url(source_url)
    parts = urlsplit(source_url)
    if parts.scheme != "https" or not parts.netloc:
        raise DownloadError("只接受 HTTPS 模型来源 URL。")
    return DownloadRequest(
        filename=filename,
        category=category,
        source_url=source_url,
        expected_sha256=normalize_sha256(expected_sha256),
        workflows=tuple(sorted(set(workflows))),
    )


def request_from_dependency_report(report_path: Path, filename: str) -> DownloadRequest:
    report = json.loads(report_path.read_text(encoding="utf-8-sig"))
    matches: list[dict[str, Any]] = []
    for row in report.get("dependencies", []):
        if row.get("filename", "").lower() != filename.lower():
            continue
        if row.get("status") != "missing":
            continue
        urls = row.get("source_urls", [])
        if row.get("expected_category") == "unknown" or len(urls) != 1:
            continue
        matches.append(row)
    unique = {(row["filename"].lower(), row["expected_category"], row["source_urls"][0]): row for row in matches}
    if not unique:
        raise DownloadError(
            "依赖报告中没有找到可安全下载的缺失模型；请先检查模型名、来源链接和类别。"
        )
    if len(unique) > 1:
        raise DownloadError("同名模型在报告中有多个类别或来源，必须先人工确认。")
    row = next(iter(unique.values()))
    return validate_request(
        filename=row["filename"],
        category=row["expected_category"],
        source_url=row["source_urls"][0],
        expected_sha256="auto",
        workflows=[ref["workflow"] for ref in row.get("references", [])],
    )


def b64(value: str) -> str:
    return base64.b64encode(value.encode("utf-8")).decode("ascii")


def remote_preamble(values: dict[str, str]) -> str:
    lines = ["set -euo pipefail", "umask 077"]
    for key, value in values.items():
        lines.append(f"{key}=$(printf %s '{b64(value)}' | base64 -d)")
    return "\n".join(lines) + "\n"


def run_remote(host: str, script: str) -> str:
    command = [
        "ssh",
        "-o", "BatchMode=yes",
        "-o", "ConnectTimeout=20",
        "-o", "ServerAliveInterval=30",
        "-o", "ServerAliveCountMax=3",
        host,
        "bash",
        "-s",
    ]
    # On Windows, text-mode stdin would translate LF to CRLF.  Bash then sees
    # ``pipefail\r`` and rejects it, so send UTF-8 bytes with Unix newlines.
    try:
        result = subprocess.run(
            command,
            input=script.encode("utf-8"),
            text=False,
            capture_output=True,
        )
    except subprocess.TimeoutExpired as exc:
        raise TransferUnavailable(f"美服 SSH 连接超时：{exc}") from exc
    if result.returncode != 0:
        stderr = (result.stderr or result.stdout).decode("utf-8", errors="replace").strip()
        if is_transient_transfer_detail(stderr, returncode=result.returncode):
            raise TransferUnavailable(f"美服连接或来源网络暂不可用：{stderr[-1200:]}")
        raise DownloadError(f"美服命令失败：{stderr[-1200:]}")
    return result.stdout.decode("utf-8", errors="replace").strip()


def verify_meifu_connection(host: str) -> None:
    """Verify a usable direct SSH session before a queue launches a model worker."""

    response = run_remote(host, "printf '%s' 'MEIFU_CONNECTION_OK'\n")
    if response != "MEIFU_CONNECTION_OK":
        raise TransferUnavailable("美服 SSH 连通性探测未返回预期结果。")


def remote_probe(host: str, cache_root: str, url: str) -> dict[str, Any]:
    script = remote_preamble({"CACHE_ROOT": cache_root, "URL": url}) + r'''
headers=$(mktemp)
trap 'rm -f "$headers"' EXIT
curl --fail --location --silent --show-error --retry 8 --retry-all-errors --retry-delay 3 \
  --connect-timeout 30 --max-time 600 --range 0-0 --dump-header "$headers" --output /dev/null "$URL"
python3 - "$headers" "$CACHE_ROOT" <<'PY'
import json, re, shutil, sys
from pathlib import Path
headers = Path(sys.argv[1]).read_text(encoding='latin-1')
pairs = re.findall(r'^([^:\r\n]+):\s*(.*?)\s*$', headers, flags=re.MULTILINE)
last = {}
for key, value in pairs:
    last[key.lower()] = value
content_range = last.get('content-range', '')
match = re.search(r'/([0-9]+)\s*$', content_range)
size = int(match.group(1)) if match else None
etag = last.get('x-linked-etag') or last.get('etag')
free = shutil.disk_usage('/').free
print(json.dumps({'size_bytes': size, 'etag': etag, 'content_range': content_range, 'remote_free_bytes': free}))
PY
'''
    response = run_remote(host, script)
    if not response.strip():
        raise TransferUnavailable("美服来源探测没有返回数据；已保留断点并等待网络恢复。")
    try:
        payload = json.loads(response)
    except json.JSONDecodeError as exc:
        if is_transient_transfer_detail(response):
            raise TransferUnavailable(f"美服来源探测收到临时上游响应：{response[-800:]}") from exc
        raise DownloadError(f"美服探测返回格式无效：{exc}") from exc
    if not isinstance(payload.get("size_bytes"), int) or payload["size_bytes"] <= 0:
        raise DownloadError("来源服务器没有提供可用的文件大小，不能安全进行分块续传。")
    return payload


def remote_fetch_chunk(
    *,
    host: str,
    cache_root: str,
    remote_part: str,
    url: str,
    start: int,
    end: int,
) -> str:
    expected_size = end - start + 1
    script = remote_preamble({
        "CACHE_ROOT": cache_root,
        "PART": remote_part,
        "URL": url,
    }) + f'''
case "$PART" in "$CACHE_ROOT"/*) ;; *) echo "非法缓存路径" >&2; exit 2;; esac
mkdir -p "$(dirname "$PART")"
expected={expected_size}
global_start={start}
current=0
if [ -f "$PART" ]; then current=$(stat -c %s "$PART"); fi
if [ "$current" -gt "$expected" ]; then rm -f -- "$PART"; current=0; fi
if [ "$current" -lt "$expected" ]; then
  remaining_start=$((global_start + current))
  set -o pipefail
  curl --fail --location --silent --show-error --retry 12 --retry-all-errors --retry-delay 5 \\
    --connect-timeout 30 --max-time 0 --range "${{remaining_start}}-{end}" "$URL" | \\
    dd of="$PART" oflag=append conv=notrunc status=none
fi
actual=$(stat -c %s "$PART")
if [ "$actual" -ne "$expected" ]; then
  rm -f -- "$PART"
  echo "分块大小异常：$actual，期望：$expected" >&2
  exit 3
fi
sha256sum "$PART" | awk '{{print $1}}'
'''
    response = run_remote(host, script)
    lines = [line.strip() for line in response.splitlines() if line.strip()]
    if not lines:
        raise TransferUnavailable("美服分块请求没有返回 SHA-256；已保留当前分块等待网络恢复。")
    digest = lines[-1].lower()
    if not SHA256_RE.fullmatch(digest):
        raise DownloadError("美服未返回有效的分块 SHA-256。")
    return digest


def remote_remove(host: str, cache_root: str, remote_path: str, *, directory: bool = False) -> None:
    script = remote_preamble({"CACHE_ROOT": cache_root, "TARGET": remote_path}) + r'''
case "$TARGET" in "$CACHE_ROOT"/*) ;; *) echo "拒绝清理缓存根目录外的路径" >&2; exit 2;; esac
if [ "$TARGET" = "$CACHE_ROOT" ]; then echo "拒绝清理缓存根目录" >&2; exit 2; fi
'''
    script += 'rm -rf -- "$TARGET"\n' if directory else 'rm -f -- "$TARGET"\n'
    run_remote(host, script)


def sftp_reget(host: str, remote_path: str, local_path: Path) -> None:
    local_path.parent.mkdir(parents=True, exist_ok=True)
    local_arg = local_path.as_posix()
    if any(char.isspace() for char in f"{remote_path}{local_arg}"):
        raise DownloadError("当前 SFTP 续传实现不支持包含空格的缓存或落盘路径。")
    batch = f"reget {remote_path} {local_arg}\n"
    command = [
        "sftp",
        "-o", "BatchMode=yes",
        "-o", "ConnectTimeout=20",
        "-o", "ServerAliveInterval=30",
        "-o", "ServerAliveCountMax=3",
        "-b", "-",
        host,
    ]
    try:
        result = subprocess.run(command, input=batch, text=True, capture_output=True)
    except subprocess.TimeoutExpired as exc:
        raise TransferUnavailable(f"本地从美服续传分块超时：{exc}") from exc
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        if is_transient_transfer_detail(detail, returncode=result.returncode):
            raise TransferUnavailable(f"本地到美服网络暂不可用：{detail[-1200:]}")
        raise DownloadError(f"本地从美服续传分块失败：{detail[-1200:]}")


def chunk_size_at(index: int, total_size: int, chunk_bytes: int) -> int:
    start = index * chunk_bytes
    return min(chunk_bytes, total_size - start)


def load_or_create_state(
    state_path: Path,
    request: DownloadRequest,
    size_bytes: int,
    target: Path,
    chunk_bytes: int,
) -> dict[str, Any]:
    expected = {
        "filename": request.filename,
        "category": request.category,
        "url_hash": request.url_hash,
        "size_bytes": size_bytes,
        "target_path": str(target),
        "chunk_bytes": chunk_bytes,
    }
    if state_path.exists():
        state = json.loads(state_path.read_text(encoding="utf-8"))
        if state.get("request") != expected:
            raise DownloadError("已有临时下载状态与本次请求不同；请保留原任务续传或人工检查后再清理。")
        return state
    state = {
        "schema": "ComfyUIModelChunkTransferStateV1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "request": expected,
        "source_url": request.safe_url,
        "expected_sha256": request.expected_sha256,
        "completed_chunks": [],
    }
    atomic_write_json(state_path, state)
    return state


def completed_bytes(state: dict[str, Any]) -> int:
    return sum(int(row["size_bytes"]) for row in state.get("completed_chunks", []))


def reconcile_partial(assembled: Path, state: dict[str, Any]) -> None:
    expected = completed_bytes(state)
    actual = assembled.stat().st_size if assembled.exists() else 0
    if actual < expected:
        raise DownloadError("本地合成文件小于已登记进度；为避免混入错误数据，拒绝继续。")
    if actual > expected:
        # A process could stop after writing a chunk but before atomically updating
        # the state.  Discard at most that unregistered tail and fetch it again.
        with assembled.open("r+b") as handle:
            handle.truncate(expected)


def append_chunk(assembled: Path, chunk: Path) -> None:
    with assembled.open("ab") as destination, chunk.open("rb") as source:
        shutil.copyfileobj(source, destination, length=8 * 1024 * 1024)
        destination.flush()
        os.fsync(destination.fileno())


def resolve_expected_hash(
    request: DownloadRequest,
    probe: dict[str, Any],
    allow_unverified_source: bool,
) -> DownloadRequest:
    if request.expected_sha256:
        return request
    etag = str(probe.get("etag") or "").strip().strip('"').lower()
    if SHA256_RE.fullmatch(etag):
        return DownloadRequest(
            filename=request.filename,
            category=request.category,
            source_url=request.source_url,
            expected_sha256=etag,
            workflows=request.workflows,
        )
    if not allow_unverified_source:
        raise DownloadError(
            "来源没有提供可用 SHA-256。请补充官方哈希，或在明确接受风险后使用 --allow-unverified-source。"
        )
    return request


def update_catalog(
    catalog_path: Path,
    request: DownloadRequest,
    target: Path,
    verified_sha256: str,
    size_bytes: int,
    selection: StorageSelection,
) -> None:
    if catalog_path.exists():
        catalog = json.loads(catalog_path.read_text(encoding="utf-8-sig"))
    else:
        catalog = {"schema": "ComfyUIModelCatalogV1", "models": []}
    if catalog.get("schema") != "ComfyUIModelCatalogV1" or not isinstance(catalog.get("models"), list):
        raise DownloadError("模型目录登记文件结构无效，未覆盖原文件。")
    row = {
        "filename": request.filename,
        "category": request.category,
        "relative_path": f"{request.category}/{request.filename}",
        "model_root": str(selection.model_root),
        "absolute_path": str(target),
        "size_bytes": size_bytes,
        "sha256": verified_sha256,
        "source_url": request.safe_url,
        "license_status": "pending_manual_verification",
        "workflows": list(request.workflows),
        "transport": "meifu_chunk_cache_sftp_reget",
        "verified_at": datetime.now(timezone.utc).isoformat(),
    }
    existing = [
        item for item in catalog["models"]
        if not (item.get("absolute_path") == row["absolute_path"] or item.get("sha256") == row["sha256"])
    ]
    existing.append(row)
    catalog["models"] = sorted(existing, key=lambda item: (item.get("category", ""), item.get("filename", "")))
    catalog["updated_at"] = datetime.now(timezone.utc).isoformat()
    atomic_write_json(catalog_path, catalog)


def print_dry_run(request: DownloadRequest, primary: Path, fallback: Path, args: argparse.Namespace) -> None:
    print(json.dumps({
        "mode": "dry_run",
        "request": {
            "filename": request.filename,
            "category": request.category,
            "source_url": request.safe_url,
            "expected_sha256": request.expected_sha256 or "auto_from_source",
            "workflow_count": len(request.workflows),
        },
        "transport": {
            "remote_host": args.host,
            "expected_hostname": args.expected_hostname,
            "proxy_route": "rejected unless --allow-proxy-route is supplied",
            "remote_cache": args.remote_cache,
            "chunk_gib": args.chunk_gib,
            "remote_reserve_gib": args.remote_reserve_gib,
            "local_resume": "sftp reget",
        },
        "storage_rule": {
            "primary_root": str(primary),
            "fallback_root": str(fallback),
            "primary_threshold_gib": args.primary_threshold_gib,
            "fallback_condition": "primary free space below threshold or insufficient for model plus staging",
        },
        "execution_required": "rerun with --execute after confirming this request",
    }, ensure_ascii=False, indent=2))


def print_probe(
    request: DownloadRequest,
    probe: dict[str, Any],
    primary: Path,
    fallback: Path,
    args: argparse.Namespace,
    route: dict[str, str],
) -> None:
    resolved = resolve_expected_hash(request, probe, args.allow_unverified_source)
    total_size = int(probe["size_bytes"])
    chunk_bytes = gib(args.chunk_gib)
    local_required = total_size + min(total_size, chunk_bytes) + gib(args.local_reserve_gib)
    selection = choose_storage(
        primary_root=primary,
        fallback_root=fallback,
        required_bytes=local_required,
        primary_threshold_gib=args.primary_threshold_gib,
    )
    print(json.dumps({
        "mode": "probe_only",
        "filename": resolved.filename,
        "category": resolved.category,
        "source_url": resolved.safe_url,
        "size_bytes": total_size,
        "expected_sha256": resolved.expected_sha256,
        "remote_free_bytes": probe["remote_free_bytes"],
        "remote_minimum_bytes": min(total_size, chunk_bytes) + gib(args.remote_reserve_gib),
        "selected_model_root": str(selection.model_root),
        "selected_staging_root": str(selection.staging_root),
        "selected_root_free_bytes": selection.free_bytes,
        "storage_reason": selection.reason,
        "ssh_route": route,
    }, ensure_ascii=False, indent=2))


def execute(request: DownloadRequest, args: argparse.Namespace, primary: Path, fallback: Path) -> None:
    ensure_transfer_not_paused(args.control_file)
    route = ensure_direct_meifu_route(args.host, args.expected_hostname, args.allow_proxy_route)
    probe = remote_probe(args.host, args.remote_cache, request.source_url)
    request = resolve_expected_hash(request, probe, args.allow_unverified_source)
    total_size = int(probe["size_bytes"])
    chunk_bytes = gib(args.chunk_gib)
    remote_required = min(total_size, chunk_bytes) + gib(args.remote_reserve_gib)
    if int(probe["remote_free_bytes"]) < remote_required:
        raise DownloadError(
            "美服缓存空间不足：需要至少 "
            f"{remote_required} 字节，当前仅 {probe['remote_free_bytes']} 字节。"
        )
    local_required = total_size + min(total_size, chunk_bytes) + gib(args.local_reserve_gib)
    selection = choose_storage(
        primary_root=primary,
        fallback_root=fallback,
        required_bytes=local_required,
        primary_threshold_gib=args.primary_threshold_gib,
    )
    target = selection.model_root / request.category / request.filename
    if target.exists():
        existing_hash = sha256_file(target)
        if request.expected_sha256 and existing_hash == request.expected_sha256:
            print(json.dumps({
                "status": "already_verified",
                "target": str(target),
                "sha256": existing_hash,
            }, ensure_ascii=False, indent=2))
            return
        raise DownloadError("目标位置已有不同文件；拒绝覆盖。请先人工核验或更改请求。")

    job_root = selection.staging_root / request.job_id
    state_path = job_root / "state.json"
    assembled = job_root / f"{request.filename}.part"
    local_chunks = job_root / "chunks"
    remote_job = f"{args.remote_cache.rstrip('/')}/{request.job_id}"
    job_root.mkdir(parents=True, exist_ok=True)
    state = load_or_create_state(state_path, request, total_size, target, chunk_bytes)
    reconcile_partial(assembled, state)
    complete = {int(row["index"]) for row in state.get("completed_chunks", [])}
    chunk_count = (total_size + chunk_bytes - 1) // chunk_bytes

    for index in range(chunk_count):
        if index in complete:
            continue
        ensure_transfer_not_paused(args.control_file)
        size = chunk_size_at(index, total_size, chunk_bytes)
        start = index * chunk_bytes
        remote_part = f"{remote_job}/parts/{index:06d}.part"
        local_part = local_chunks / f"{index:06d}.part"
        remote_hash = remote_fetch_chunk(
            host=args.host,
            cache_root=args.remote_cache,
            remote_part=remote_part,
            url=request.source_url,
            start=start,
            end=start + size - 1,
        )
        # If a pause arrives while Meifu was fetching, keep this one verified
        # remote piece for the later resume instead of starting local traffic.
        ensure_transfer_not_paused(args.control_file)
        sftp_reget(args.host, remote_part, local_part)
        if local_part.stat().st_size != size:
            raise DownloadError(f"本地分块 {index} 大小不符，保留临时文件等待续传。")
        local_hash = sha256_file(local_part)
        if local_hash != remote_hash:
            local_part.unlink(missing_ok=True)
            raise DownloadError(f"分块 {index} 校验失败，已删除本地损坏分块，可重新执行续传。")
        append_chunk(assembled, local_part)
        state["completed_chunks"].append({"index": index, "size_bytes": size, "sha256": local_hash})
        state["completed_chunks"].sort(key=lambda row: int(row["index"]))
        atomic_write_json(state_path, state)
        local_part.unlink(missing_ok=True)
        remote_remove(args.host, args.remote_cache, remote_part)
        print(json.dumps({
            "status": "chunk_verified",
            "chunk": index + 1,
            "chunk_count": chunk_count,
            "bytes_complete": completed_bytes(state),
            "total_bytes": total_size,
        }, ensure_ascii=False))

    ensure_transfer_not_paused(args.control_file)
    if assembled.stat().st_size != total_size:
        raise DownloadError("所有分块完成后，本地合成文件大小仍不正确。")
    verified_sha256 = sha256_file(assembled)
    if request.expected_sha256 and verified_sha256 != request.expected_sha256:
        raise DownloadError("完整模型 SHA-256 不匹配；保留临时文件和状态，未写入模型目录。")
    target.parent.mkdir(parents=True, exist_ok=True)
    os.rename(assembled, target)
    update_catalog(args.catalog, request, target, verified_sha256, total_size, selection)
    shutil.rmtree(job_root)
    remote_remove(args.host, args.remote_cache, remote_job, directory=True)
    print(json.dumps({
        "status": "completed",
        "target": str(target),
        "size_bytes": total_size,
        "sha256": verified_sha256,
        "storage_reason": selection.reason,
        "ssh_route": route,
        "remote_cache_cleaned": remote_job,
    }, ensure_ascii=False, indent=2))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    request_group = parser.add_argument_group("模型请求")
    request_group.add_argument("--dependency-report", type=Path)
    request_group.add_argument("--model", help="依赖报告中的缺失模型文件名")
    request_group.add_argument("--url", help="人工确认后的 HTTPS 直链")
    request_group.add_argument("--filename", help="与 --url 一起使用的文件名")
    request_group.add_argument("--category", help="与 --url 一起使用的 ComfyUI 模型类别")
    request_group.add_argument("--sha256", default="auto", help="官方 SHA-256；默认尝试从来源 ETag 自动发现")
    request_group.add_argument("--allow-unverified-source", action="store_true")
    transport = parser.add_argument_group("中转设置")
    transport.add_argument("--host", default=DEFAULT_HOST)
    transport.add_argument(
        "--expected-hostname",
        default="192.129.128.54",
        help="美服 SSH 别名应直接解析到的地址；空字符串可关闭地址比对。",
    )
    transport.add_argument(
        "--allow-proxy-route",
        action="store_true",
        help="允许 SSH ProxyJump/ProxyCommand；默认拒绝，防止意外经 CN2 或其他跳板中转。",
    )
    transport.add_argument("--remote-cache", default=DEFAULT_REMOTE_CACHE)
    transport.add_argument("--chunk-gib", type=float, default=DEFAULT_CHUNK_GIB)
    transport.add_argument("--remote-reserve-gib", type=float, default=DEFAULT_REMOTE_RESERVE_GIB)
    storage = parser.add_argument_group("本地落盘设置")
    storage.add_argument("--shared-paths-config", type=Path, default=DEFAULT_SHARED_PATHS)
    storage.add_argument("--primary-root", type=Path)
    storage.add_argument("--fallback-root", type=Path)
    storage.add_argument("--primary-threshold-gib", type=int, default=DEFAULT_PRIMARY_THRESHOLD_GIB)
    storage.add_argument("--local-reserve-gib", type=float, default=DEFAULT_LOCAL_RESERVE_GIB)
    storage.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument(
        "--control-file",
        type=Path,
        help="队列暂停控制文件；出现 pause/stop 时在下一个安全边界返回 75，不清除续传状态。",
    )
    parser.add_argument("--probe-only", action="store_true", help="只验证来源范围、哈希线索和存储容量，不创建缓存")
    parser.add_argument("--execute", action="store_true", help="允许创建缓存、传输和写入模型目录")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.execute:
        print(json.dumps({
            "status": "retired",
            "error": "ComfyUI 旧直连下载器已停用；请使用 delegate_model_downloads.py prepare 后由通用 Meifu 队列处理。",
        }, ensure_ascii=False), file=sys.stderr)
        return 2
    print(json.dumps({
        "status": "retired_no_op",
        "message": "ComfyUI 旧直连下载器已迁移；未连接 Meifu、未创建缓存、未写入模型。",
        "replacement": "使用 delegate_model_downloads.py prepare/status/reconcile。",
    }, ensure_ascii=False))
    return 0
    # The retained implementation below is intentionally unreachable.  It is
    # kept only for auditing legacy queue state until that state is explicitly
    # retired by the user.
    try:
        if args.url:
            if not (args.filename and args.category):
                raise DownloadError("使用 --url 时必须同时给出 --filename 和 --category。")
            request = validate_request(args.filename, args.category, args.url, args.sha256)
        else:
            if not (args.dependency_report and args.model):
                raise DownloadError("请提供 --dependency-report 加 --model，或提供 --url、--filename、--category。")
            request = request_from_dependency_report(args.dependency_report, args.model)
        primary, fallback = choose_primary_and_fallback(
            config_path=args.shared_paths_config,
            primary_override=args.primary_root,
            fallback_override=args.fallback_root,
        )
        if args.probe_only and args.execute:
            raise DownloadError("--probe-only 不能与 --execute 同时使用。")
        if args.probe_only:
            route = ensure_direct_meifu_route(args.host, args.expected_hostname, args.allow_proxy_route)
            probe = remote_probe(args.host, args.remote_cache, request.source_url)
            print_probe(request, probe, primary, fallback, args, route)
            return 0
        if not args.execute:
            print_dry_run(request, primary, fallback, args)
            return 0
        execute(request, args, primary, fallback)
        return 0
    except PauseRequested as exc:
        print(json.dumps({
            "status": "paused",
            "error": str(exc),
            "control_file": str(args.control_file) if args.control_file else None,
            "resume": "移除或改写控制文件后，重新运行同一队列即可续传。",
        }, ensure_ascii=False), file=sys.stderr)
        return 75
    except TransferUnavailable as exc:
        print(json.dumps({
            "status": "waiting_for_network",
            "error": str(exc),
            "resume": "已保留本地状态和美服当前分块；网络恢复后运行同一队列即可续传。",
        }, ensure_ascii=False), file=sys.stderr)
        return TEMPORARY_TRANSFER_EXIT_CODE
    except (DownloadError, OSError, json.JSONDecodeError, subprocess.SubprocessError) as exc:
        print(json.dumps({"status": "failed", "error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
