import assert from "node:assert/strict";
import { SourceDownloadObservation, beginSourceDownloadObservation, observeSourceDownloadAction } from "./browser_download_observer.mjs";

const origin = "https://source.example.test";
const event = (method, params) => ({ method, params });
const response = event("Network.responseReceived", { requestId: "fixture-request", response: { url: `${origin}/api/blade-fileserver/api/fileserver/usualDownloadFile`, status: 200, mimeType: "application/octet-stream", headers: { "Content-Length": "400", "Set-Cookie": "synthetic-secret-must-not-leak" } } });
const begin = event("Page.downloadWillBegin", { guid: "fixture-guid", suggestedFilename: "fixture.zip", url: `blob:${origin}/fixture` });
const finish = event("Network.loadingFinished", { requestId: "fixture-request", encodedDataLength: 900 });
const progress = event("Page.downloadProgress", { guid: "fixture-guid", state: "canceled", receivedBytes: 0, totalBytes: 400 });
const observed = new SourceDownloadObservation(origin);
observed.accept(response);
observed.accept(event("Network.dataReceived", { requestId: "other-request", dataLength: 10000 }));
observed.accept(event("Network.dataReceived", { requestId: "fixture-request", dataLength: 400 }));
observed.accept(begin);
observed.accept(progress);
assert.equal(observed.result(), null);
observed.accept(finish);
assert.equal(observed.result().status, "BLOB_CANCELED_ZERO");
assert.equal(observed.result().dataBytes, 400);
assert.equal(JSON.stringify(observed.result()).includes("synthetic-secret"), false);
assert.equal(JSON.stringify(observed.result()).includes("blob:"), false);
observed.accept(event("Page.downloadProgress", { guid: "fixture-guid", state: "completed", receivedBytes: 400, totalBytes: 400 }));
assert.equal(observed.result().status, "NATIVE_COMPLETED");
const incomplete = new SourceDownloadObservation(origin);
for (const value of [response, begin, finish, progress]) incomplete.accept(value);
assert.equal(incomplete.result().code, "DOWNLOAD_LENGTH_EVIDENCE_MISMATCH");
const ambiguous = new SourceDownloadObservation(origin);
ambiguous.accept(response);
ambiguous.accept({ ...response, params: { ...response.params, requestId: "second-request" } });
assert.equal(ambiguous.result().code, "DOWNLOAD_RESPONSE_AMBIGUOUS");
const auth = new SourceDownloadObservation(origin);
auth.accept({ ...response, params: { ...response.params, response: { ...response.params.response, status: 401 } } });
assert.equal(auth.result().code, "SOURCE_AUTH_EXPIRED");
assert.throws(() => new SourceDownloadObservation("https://user:secret@source.example.test"), /DOWNLOAD_ORIGIN_INVALID/);
let reads = 0;
const batches = [[], [response], [event("Network.dataReceived", { requestId: "fixture-request", dataLength: 200 })], [event("Network.dataReceived", { requestId: "fixture-request", dataLength: 200 }), begin, finish, progress]];
const cdp = { readEvents: async (options) => { const n = reads++; if (n) assert.equal(options.afterSequence, n - 1); return { cursor: n, events: batches[n], truncated: false, hasMore: false }; } };
const active = await beginSourceDownloadObservation(cdp, { origin });
assert.equal((await active.done).status, "BLOB_CANCELED_ZERO");
assert.equal(reads, 4);
let truncatedCalls = 0;
const evicted = await beginSourceDownloadObservation({ readEvents: async () => ({ cursor: truncatedCalls++, events: [], truncated: truncatedCalls > 1 }) }, { origin });
assert.equal((await evicted.done).code, "DOWNLOAD_RESPONSE_EVIDENCE_EVICTED");
reads = 0;
let clicks = 0;
const oneAction = await observeSourceDownloadAction(cdp, { origin, action: async () => { clicks += 1; } });
assert.equal(oneAction.status, "BLOB_CANCELED_ZERO");
assert.equal(clicks, 1);
await assert.rejects(observeSourceDownloadAction(cdp, { origin, action: async () => {}, timeoutMs: 60000 }), /DOWNLOAD_ACTION_ARGUMENT_INVALID/);
console.log("browser download observer: correlated lengths, privacy, continuous drain and fail-closed checks passed");
